version: '3.9'
services:
  db:
    image: 'postgres'
    ports:
      - '4321:5432'
    environment:
      POSTGRES_PASSWORD : 'template_password'
      POSTGRES_USER : 'template_user'
      POSTGRES_DB : 'template_db'
    volumes:
      - data:/var/lib/postgresql/data

volumes:
  data: 